### PR TITLE
Use macro callsite spans in backtrace

### PR DESCRIPTION
**Pull request by Aaron1011**
This mirrors what we do in the debuginfo used for runtime backtraces.

### CODE REVIEW

**Comment by oli-obk** [comment]
Nice!

@bors r+

**Comment by RalfJung** [comment]
@pietroalbini @lzutao looks like gating on GHA didn't work properly? CI passed fine but bors did not notice...

**Comment by pietroalbini** [comment]
@RalfJung https://github.com/rust-lang/miri/pull/1571 is not merged yet

**Comment by RalfJung** [comment]
> @RalfJung #1571 is not merged yet

Sure but that should not be a problem -- we have a dummy GHA job.

**Comment by pietroalbini** [comment]
@RalfJung bors is listening for a job named "bors build finished", which is currently not present.

**Comment by RalfJung** [comment]
Yeah I am trying to add one in https://github.com/rust-lang/miri/pull/1576... the dummy job @lzutao was supposed to be enough but it seems it is not.

**Pull request merged**
