### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by RalfJung**
Locally tests pass but rustc CI says they fail, let's see what happens...

Also clarify docs of cmpxchg_weak_failure_rate (Cc https://github.com/rust-lang/miri/issues/2160).

### CODE REVIEW

**Comment by RalfJung** [comment]
Ah, tons of failures because dead stores get removed since https://github.com/rust-lang/rust/pull/97158.

@oli-obk I wonder if it still makes sense to run the compile-fail test suite with optimizations? We will have to add `black_box` to more and more tests to prevent UB from being optimized away.

**Comment by JakobDegen** [comment]
Yeah, it doesn't seem to make much sense to run compile-fail tests with optimizations, since post optimization code is not expected to reproduce UB. I'd be happy to do the work of putting up a PR that fixes things via `#[inline(never)]` or `black_box` or such, but at that point I'm not really sure what we're testing.

**Comment by RalfJung** [comment]
All right. I disabled the opt tests entirely for now; once https://github.com/rust-lang/miri/issues/2155 is fixed we can run the pass and panic tests without running the fail tests.

**Pull request merged**
