### PR TITLE
Add `#![feature(yeet_expr)]`

### PR DESCRIPTION
**Pull request by scottmcm**
Hopefully enough for https://github.com/rust-lang/rust/issues/98036

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks! Could you also update the `rust-version` file so the new rustc is actually picked up?

**Comment by scottmcm** [comment]
Ah, sure.  I assume I need to wait for the nightly to come out for that?

**Comment by RalfJung** [comment]
No, we are using rustup-toolchain-install-master.

**Comment by scottmcm** [comment]
Sorry, I should have actually looked at the file 😬

Done.  Hopefully CI will approve.

**Pull request merged**
