### PR TITLE
many-seeds: propagate failure properly

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/miri/issues/3405.

### CODE REVIEW

**Comment by RalfJung** [comment]
Okay so now it indeed does fail on Windows. But not in a useful way:
```
 Error: io error when running command `./miri run tests/many-seeds/scoped-thread-leak.rs`: %1 is not a valid Win32 application. (os error 193)
```
@ChrisDenton can `Command` not spawn scripts on Windows? Would it work to run the batch script instead of the bash script?

**Comment by ChrisDenton** [comment]
On Windows you can only reliably run exe files.

https://github.com/rust-lang/rust/issues/94743 has some more details (though ultimately adding support for scripts was not popular)

**Comment by RalfJung** [comment]
Then either we can get bash to launch the script for us or we'll have to disable the test on Windows. I don't want to duplicate the logic from './miri' that computes where the binary is.

**Comment by RalfJung** [comment]
This might work...
@bors r+

**Pull request merged**
