### PR TITLE
Issue#2347

### PR DESCRIPTION
**Pull request by badumbatish**
Created as a draft since I need to hande env of cargo_extra_flags. Would love some ci :) hehe

### CODE REVIEW

**Comment by badumbatish** [comment]
it seems my rebase did sth really wrong..

**Comment by saethlin** [comment]
Usually this happens because you rebased over a stale fetch of upstream's master branch, or you tried to rebase a merge commit. Rebasing a merge commit doesn't make a lot of sense conceptually and git doesn't offer help untangling your request when you try to. You should always rebase up branches with `git pull --rebase https://github.com/rust-lang/miri` or swap in the ssh URL if you want.

The for-sure way out of this is to interactive rebase over an up-to-date fetch and change all but the top `pick` to `f`. That will combine all the commits together, which is what you want anyway.

**Comment by RalfJung** [comment]
Please also update the issue title and description to explain what the PR does. :)

It's okay to mention the issue in the PR description, but the PR title should be self-explaining.

**Comment by badumbatish** [comment]
Will do!

**Comment by badumbatish** [comment]
@saethlin i'm not sure how to reconcile this, i'll close this PR and cherry pick relevant commits to a new PR

**Comment by saethlin** [comment]
> The for-sure way out of this is to interactive rebase over an up-to-date fetch and change all but the top `pick` to `f`. That will combine all the commits together, which is what you want anyway.

The ultimate way to dig out of a confused rebase is this ^

Whatever cherry-pick workflow you're doing could be done to this PR's' branch too. You'd build a new branch in the state you want then hard-reset this PR's branch to that new branch, and force-push to the PR. GitHub prevents you from reopening a PR if you force-push to it while it's closed though, so you probably don't want to try that.

**Comment by badumbatish** [comment]
I tried to rebase (I git pull upstream master in this branch first) but the rebase list option is riddle with commits thats not mine in between, so i'm not sure how to change all f to p except the first one); example is below
```
pick 56fbbcbf1 detect when pthread_rwlock_t is moved
pick a67607b9e sync methods: pass around places, not pointer-typed operands
pick 59f68710a sync: store extra sync primitive data in a Box<dyn Any> so the type can be kept local
pick 5984313b2 Fetch miri flags from cargo config (relevant commit)
pick f67d10d0c Add tests for fetching flags from from cargo config (relevant commit)
pick 7020cd2ef Add info on setting miriflags in cargo config (relevant commit)
pick 7bebd05cf empty commit to go through bors # empty 
pick 65444952b tests/run-make: update to use fs_wrapper # empty
pick 821d97909 Move get_miri_flags to util.rs (mine)
pick a77abd343 Update pseudo-flag and better comments (mine)
pick 08a6d3f1b Fix build warnings of unused (mine)

# Rebase e4cf56ad1..08a6d3f1b onto e4cf56ad1 (11 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup [-C | -c] <commit> = like "squash" but keep only the previous
#                    commit's log message, unless -C is used, in which case
#                    keep only this commit's message; -c is same as -C but
#                    opens the editor
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
#         create a merge commit using the original merge commit's
#         message (or the oneline, if no original merge commit was
#         specified); use -c <commit> to reword the commit message
# u, update-ref <ref> = track a placeholder for the <ref> to be updated
#                       to this position in the new commits. The <ref> is
#                       updated at the end of the rebase
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
# 
```

I think the cherry pick option is better for now but it'd be nice to get some help on this. I'm gonna open a new PR to avoid sending notifications to all unrelevant participants everytime we corespond on this pr

**Comment by saethlin** [comment]
> I git pull upstream master in this branch first

By default, this command turns your commit history into spaghetti, which becomes impossible to untangle later. I only `git pull --rebase` because I prefer my spaghetti in a bowl.

> but the rebase list option is riddle with commits thats not mine in between

Ah sorry. You'll want to reword the commit message on the resultant commit, you can do this by setting the top pick up `reword` or `r` or by doing a `git commit --amend` after the rebase.

I don't know if I'm being helpful, but truly the only way I know out of a scuffed rebase is to rebase more. If you're not comfortable trying N different rebases to see what happens, you'll have trouble getting unstuck from some situations. Maybe that's fine, but I'm a rebase lover.

**Comment by badumbatish** [comment]
> > I git pull upstream master in this branch first
> 
> By default, this command turns your commit history into spaghetti, which becomes impossible to untangle later. I only `git pull --rebase` because I prefer my spaghetti in a bowl.
> 
> > but the rebase list option is riddle with commits thats not mine in between
> 
> Ah sorry. You'll want to reword the commit message on the resultant commit, you can do this by setting the top pick up `reword` or `r` or by doing a `git commit --amend` after the rebase.
> 
> I don't know if I'm being helpful, but truly the only way I know out of a scuffed rebase is to rebase more. If you're not comfortable trying N different rebases to see what happens, you'll have trouble getting unstuck from some situations. Maybe that's fine, but I'm a rebase lover.

i still keep this broken branch on my forkk so i'll keep on rebasing :) tysm

**Pull request closed without merging**
