### PR TITLE
Rustup to rustc 1.42.0-nightly (9ff30a781 2019-12-21)

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by RalfJung** [comment]
Curious, but why did this change?

@bors r+

**Comment by RalfJung** [comment]
Oh, could it be https://github.com/rust-lang/rust/pull/64588 ? @matthewjasper did that PR change desugaring for `ptr as *mut _`/`ptr as *const _`?

**Comment by matthewjasper** [comment]
Yes, it did. `let p = x as *mut u32;` is now `let p = &raw mut *x`

**Comment by RalfJung** [comment]
Curiously though, only with https://github.com/rust-lang/rust/pull/67532 did the rustc toolstate change...

**Comment by oli-obk** [comment]
there was a toolstate bug and toolstate got fixed in that rollup

**Pull request merged**
