### PR TITLE
Handle post-merge comments of AVX2 PR

### PR DESCRIPTION
**Pull request by eduardosm**

### CODE REVIEW

**Comment by RalfJung** [comment]
Do you plan to look into [this comment](https://github.com/rust-lang/miri/pull/3492#discussion_r1581786439) as well?

**Comment by eduardosm** [comment]
I am getting a test failure, but I don't see how it is related.

```
error: pass test got exit status: 101, but expected 0

error: actual output differed from expected
Execute `./miri test --bless` to update `tests/pass-dep/shims/libc-misc.stderr` to the actual output
--- tests/pass-dep/shims/libc-misc.stderr
+++ <stderr output>
+thread 'main' panicked at $DIR/libc-misc.rs:LL:CC:
+assertion `left == right` failed
+  left: 9
+ right: 7
+stack backtrace:
+   0: std::panicking::begin_panic_handler
+ at RUSTLIB/std/src/panicking.rs:LL:CC
+   1: core::panicking::panic_fmt
+ at RUSTLIB/core/src/panicking.rs:LL:CC
+   2: core::panicking::assert_failed_inner
+ at RUSTLIB/core/src/panicking.rs:LL:CC
+   3: core::panicking::assert_failed
+ at RUSTLIB/core/src/panicking.rs:LL:CC
+   4: test_localtime_r
+ at $DIR/libc-misc.rs:LL:CC
+   5: main
+ at $DIR/libc-misc.rs:LL:CC
+   6: <fn() as std::ops::FnOnce<()>>::call_once - shim(fn())
+ at RUSTLIB/core/src/ops/function.rs:LL:CC
+note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


full stderr:
thread 'main' panicked at tests/pass-dep/shims/libc-misc.rs:243:5:
assertion `left == right` failed
  left: 9
 right: 7
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /home/eduardosm/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /home/eduardosm/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /home/eduardosm/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/panicking.rs:409:17
   3: core::panicking::assert_failed::<i32, i32>
             at /home/eduardosm/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/panicking.rs:364:5
   4: test_localtime_r
             at tests/pass-dep/shims/libc-misc.rs:243:5
   5: main
             at tests/pass-dep/shims/libc-misc.rs:412:5
   6: <fn() as std::ops::FnOnce<()>>::call_once - shim(fn())
             at /home/eduardosm/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

full stdout:
```

**Comment by saethlin** [comment]
The test suite also fails for me locally, and it fails differently. I suspect this is just a bug in the `localtime_r` shim.

**Comment by RalfJung** [comment]
Thanks!
@bors r+

**Pull request merged**
