### PR TITLE
Fix fallout from rust-lang/rust#85557

### PR DESCRIPTION
**Pull request by hyd-dev**
This is a *very small* PR for toolstate only, and does not implement the `-Zmiri` flag -- that will require more work.

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks, but I think this won't even be needed since you added a default implementation in the trait. :)

**Comment by hyd-dev** [comment]
> you added a default implementation in the trait

I think I didn't? https://github.com/rust-lang/rust/pull/85557/files#diff-e9daf17f74c5b3adb35982fc1d56b04cd37d382bffec1ed3463d02ff85bbfa8aR136

**Comment by RalfJung** [comment]
Ah, I misread... could you please add one? I don't know why we didn't do it for the others, but here I feel very much like we want one.

**Comment by hyd-dev** [comment]
Added one, so this can be closed.

**Pull request closed without merging**
