### PR TITLE
add Miri build script

### PR DESCRIPTION
**Pull request by RalfJung**
For some time now I have used some home-grown scripts to make hacking on Miri a bit easier. That seems like something that others might also find useful!

~~For now, this is only tested on Linux (and some of it will very likely not work on macOS).~~ We also use this on CI, making sure it really works (on Linux + macOS).

### CODE REVIEW

**Comment by oli-obk** [comment]
hmm... can you add some use of that script to the linux builders? Maybe by replacing an existing manual invocation of the steps?

**Comment by RalfJung** [comment]
Sadly this adds 90s to our CI time because we build Miri first with `--all-features` and then without :/

**Comment by oli-obk** [comment]
why not build it with `--all-features` both times?

**Comment by RalfJung** [comment]
Later when we do `./miri test` I don't see a good way to pass the `--all-features` to all the build steps (the sysroot preparation in particular).

**Comment by RalfJung** [comment]
Seems to cost even 3min of CI time on macOS. :/

**Comment by RalfJung** [comment]
All right, the script is now used on CI and CI is green. And a bit slower than before.

**Comment by oli-obk** [comment]
needs a rebase, but r=me otherwise

**Pull request merged**
