### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by RalfJung**
No change needed, just making sure that the nightly CI failure truly was spurious.

### CODE REVIEW

**Comment by bjorn3** [comment]
```
error: missing component `rustc` on toolchain `0f5c76951327b912c8e92e83235430ebd9b349d9` on channel `nightly` for target `i686-pc-windows-msvc`
```

**Comment by RalfJung** [comment]
oO
That target is also missing entirely in the last nightly according to https://rust-lang.github.io/rustup-components-history/i686-pc-windows-msvc.html.

**Comment by RalfJung** [comment]
Closing this then, https://github.com/rust-lang/rust/issues/76638 tracks the missing rustup packages.

**Pull request closed without merging**
