### PR TITLE
attempt to overwrite globally set build.rustc-wrapper

### PR DESCRIPTION
**Pull request by RalfJung**
Hopefully fixes https://github.com/rust-lang/miri/issues/2429

### CODE REVIEW

**Comment by saethlin** [comment]
This PR broke the `nextest` support. `cargo miri nextest list` now does this:
```
   Compiling scratch v0.1.0 (/tmp/scratch)
    Finished test [unoptimized + debuginfo] target(s) in 0.10s
error: creating test list failed

Caused by:
  for `scratch::bin/scratch`, running command `/tmp/scratch/target/miri/x86_64-unknown-linux-gnu/debug/deps/scratch-8097932b18eafdc6 --list --format terse` failed to execute

Caused by:
  Permission denied (os error 13)
```
`list` is the first step of `nextest run`. Any crate with any test seems to work as a reproducer.

It looks like something, probably `nextest`, is now trying to `execve` one of the JSON files.

**Comment by RalfJung** [comment]
Are you sure it was this change, not https://github.com/rust-lang/miri/pull/2428 ?

**Pull request merged**
