### PR TITLE
Fix project dirs path

### PR DESCRIPTION
**Pull request by soc**
ProjectDirs::from("miri", "miri", "miri")

would get you `miri\miri` on Windows and `miri.miri.miri` on macOS.

I'm assuming here that your intention was to have only a `miri` directory on every OS.

### CODE REVIEW

**Comment by RalfJung** [comment]
So on Linux, this remains at `~/.cache/miri`?

To fix Windows CI, you'll have to [adjust the path here](https://github.com/rust-lang/miri/blob/4736692e67f989ed034de6761040bd2bf850040e/.appveyor.yml#L39).

**Comment by soc** [comment]
@RalfJung Yes. The arguments for `ProjectDirs::from` are `qualifier: &str, organization: &str, application: &str`, not e. g. `linux: &str, macos: &str, windows: &str`.

**Comment by RalfJung** [comment]
I see. Would it make sense for us to use "rust" or "rust-lang" as "organization"?
I don't know what "qualifier" is supposed to mean.

**Comment by soc** [comment]
Qualifier is for macOS so that `ProjectDirs::from("com", "Foo Corp",  "Bar App")` gets you

    Lin: /home/alice/.config/barapp
    Win: C:\Users\Alice\AppData\Roaming\Foo Corp\Bar App\config
    Mac: /Users/Alice/Library/Preferences/com.Foo-Corp.Bar-App

**Comment by RalfJung** [comment]
TBH I care very little about how our paths look like on macOS.^^ I was just wondering what makes most sense.

**Comment by RalfJung** [comment]
Nobody seemed to care much when I asked on Zulip. So I'd say let's go with `org.rust-lang.miri` on macOS, unless @oli-obk objects.

**Comment by oli-obk** [comment]
> unless @oli-obk objects.

quite the opposite, let's do this

**Comment by RalfJung** [comment]
@soc okay so can you make this `"org", "rust-lang", "miri"`? That will have the effect of using `org.rust-lang.miri` on macOS and `rust-lang\miri` on Windows, right?

**Comment by soc** [comment]
@RalfJung Sorry for the delay, your commit looks good to me. Thanks!

**Comment by RalfJung** [comment]
No trouble, and thanks for pointing out that we were using this API the wrong way. :)

**Comment by soc** [comment]
It's been a pleasure! No I just need to fix cargo and the rest of the ecosystem. :-)

**Pull request merged**
