### PR TITLE
Add more bench-cargo-miri programs

### PR DESCRIPTION
**Pull request by saethlin**
These example programs are derived from long-running (>15 minutes) tests in the test suites of highly-downloaded crates (if I have my way, that runtime will not be correct for long). They should serve as realistic but also somewhat pathological workloads for the interpreter.

The unicode program stresses the code which looks for adjacent and equal stacks to merge them.
The backtraces program has an uncommonly large working set of borrow tags per borrow stack.

This also updates the .gitignore to ignore files commonly emitted in the course of using these benchmark programs.

---

The benchmark programs are so-named to avoid confusingly duplicating the names of the crates they are benchmarking. Is that a good idea? I started doing this so that I could use `cargo add` but now I'm not entirely sold on the names.

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks! Have you made sure that this is fine license-wise, i.e. either they use the same (or more permissive) license as Miri or have a local copy of their respective license?

> The benchmark programs are so-named to avoid confusingly duplicating the names of the crates they are benchmarking. Is that a good idea? I started doing this so that I could use cargo add but now I'm not entirely sold on the names.

What else would they be named?

>  long-running (>15 minutes) tests

So these benchmarks take 15min...? Or did you reduce them to a size that one can actually usefully benchmark?

**Comment by RalfJung** [comment]
Oh, you just copied the tests, but the actual code is in the crates. Then I guess there is no license problem. But there is a benchmark stability problem, we might want to ensure that we lock a particular version of these dependecies?

**Comment by saethlin** [comment]
> So these benchmarks take 15min...? Or did you reduce them to a size that one can actually usefully benchmark?

I reduced them to a reasonable size where required. I just checked, they run in less than 30 seconds on the latest Miri.

**Comment by RalfJung** [comment]
Looking good, thanks!
@bors r+

**Pull request merged**
