### PR TITLE
Place projection field is now Box<[PlaceElem<'tcx>]>

### PR DESCRIPTION
**Pull request by spastorino**
Closes https://github.com/rust-lang/rust/issues/64441

### CODE REVIEW

**Comment by oli-obk** [comment]
Please update the rust-version file, too so CI picks it up

**Comment by RalfJung** [comment]
That'll not work though, due to https://github.com/rust-lang/rust/issues/64410.

**Comment by RalfJung** [comment]
I added a work-around for the backtrace issue.

@spastorino can you rebase, and then put the rust commit hash against which you tested into `rust-version`?

**Comment by spastorino** [comment]
Done!

**Comment by RalfJung** [comment]
Thanks!

@bors r+

**Pull request merged**
