### PR TITLE
Refactor POSIX to UNIX

### PR DESCRIPTION
**Pull request by InfRandomness**
This renames the directories containing posix to unix; where applicable,
it also rename functions with the word "posix" to "unix"

Fixes https://github.com/rust-lang/miri/issues/2012

### CODE REVIEW

**Comment by RalfJung** [comment]
LGTM. :)

> This PR is blocked until the merging of https://github.com/rust-lang/miri/pull/2011

@landaire said they can deal with the conflicts. So I'd be fine landing this any time. I'm always happy to reduce the size of our PR list. ;)

**Comment by InfRandomness** [comment]
Fixes #2012

**Comment by RalfJung** [comment]
> Fixes https://github.com/rust-lang/miri/issues/2012

This needs to go into the main PR comment; I have edited it accordingly.

**Comment by RalfJung** [comment]
Bors keeps missing r+'s recently...
@bors r+

**Pull request merged**
