### PR TITLE
Don't print stacktraces with only one frame

### PR DESCRIPTION
**Pull request by saethlin**
Currently, we get diagnostics that look like this:
```
error: Undefined Behavior: no item granting read access to tag <untagged> at alloc994 found in borrow stack.
 --> src/main.rs:5:23
  |
5 |     unsafe { let _z = *y; }
  |                       ^^ no item granting read access to tag <untagged> at alloc994 found in borrow stack.
  |
  = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
  = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
          
  = note: inside `main` at src/main.rs:5:23

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error
```
This line:
```
  = note: inside `main` at src/main.rs:5:23
```
 is the trimmed backtrace. But when there's only one frame, we don't need it at all. This PR removes it, along with its extra newline.
 
We could also always skip the first element of the stacktrace (because we always print a span for it). Should we?

### CODE REVIEW

**Comment by RalfJung** [comment]
There's nothing fundamentally different about 1-frame stack traces so I don't think we should special-case them.

However, it is true that our backtrace is a bit odd... the reason we print the first frame at all is that it contains one bit of information that is not otherwise present: the name of the function the error occurred in. It didn't seem right to name all functions except for the one with the error, so that's why I made it print that span again.

**Comment by saethlin** [comment]
Ah. So what I want here is to fold the function name of the topmost frame into the ` --> src/main.rs:5:23`, but I don't think that is possible with the current API. _grumble grumble_

**Comment by RalfJung** [comment]
Yeah that would indeed be best.

Any other ideas? :D

**Comment by saethlin** [comment]
I asked the diagnostics people about this on Zulip and Esteban said the only real option here is to mash the file name into the diagnostic text. Gah. I'll just quietly be bothered by this. Perhaps when `Span` starts to know about the function it is in there will be some helpful changes on the rustc side.

**Pull request closed without merging**
