### PR TITLE
add option to track call IDs

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by oli-obk** [comment]
would be nice if we had a reasonable scheme for testing these things at some point. Maybe we could use the stderr regex replacement schemes to hide the actual ids?

**Comment by RalfJung** [comment]
Sure, would be nice -- but also I don't think we have ever had trouble with a bug in these tracking flags.

**Comment by RalfJung** [comment]
I removed the rustup as it actually requires a test change; will do that separately.

Fine to land as-is?

**Comment by oli-obk** [comment]
Looks fine to me. Do you know if it's possible to detect a protector-caused stacked borrows violation and thus add a suggestion to the diagnostic telling you to add the new flag to your invocation to learn more?

**Comment by RalfJung** [comment]
Yes, that is possible. It's this code path:

https://github.com/rust-lang/miri/blob/e7ef64fb7477cc77d5b32e7060690c0c9c54015b/src/stacked_borrows.rs#L290

**Pull request merged**
