### PR TITLE
retag return place

### PR DESCRIPTION
**Pull request by RalfJung**
@eddyb suggested that return places should be treated like unique references for Stacked Borrows. That is implemented by this patch, but it is unfortunately quite the hack because otherwise we are retagging *references*, not places.

@eddyb does this roughly correspond to what you had in mind? (Except for whatever it is you think should happen with argument passing, which is a much bigger issue.) Also, do you think there is any way we can *test* this?

Needs https://github.com/rust-lang/rust/pull/71100 to land.

### CODE REVIEW

**Comment by eddyb** [comment]
> Also, do you think there is any way we can test this?

You want to a raw pointer to some `place` (so that borrowck doesn't catch it) then `place = foo()`.
But it might not be possible to make the call terminator not use a temporary, without NRVO.

**Comment by RalfJung** [comment]
Yeah, this creates a temporary:
```rust
fn foo(_ptr: *mut i32) -> i32 { 4 }

fn main() {
    let mut ret = 0i32;
    let ptr = &mut ret as *mut _;
    ret = foo(ptr);
}
```

**Comment by eddyb** [comment]
I'm not entirely sure why we do that, don't we make temporaries for all the non-constant args?
Feels like overkill. cc @nikomatsakis

**Pull request merged**
