### PR TITLE
pass clippy::integer_arithmetic in our shims

### PR DESCRIPTION
**Pull request by RalfJung**
@oli-obk [raised some concerns](https://github.com/rust-lang/miri/pull/2422#discussion_r928220546) about this one. I still think it is the right call, since I don't see a good way to enable overflow checks for our official release builds. I'm open to suggestions though!

Fixes https://github.com/rust-lang/miri/issues/1236

### CODE REVIEW

**Comment by oli-obk** [comment]
I looked into it and I see no reason why we can't just add `debug-assertions=true` to the `[profile.release]` section of our `Cargo.toml`.

**Comment by RalfJung** [comment]
We just recently stopped using profiles because they dont work in workspaces - only the profile in the workspace root Cargo.toml is taken into account.

**Comment by oli-obk** [comment]
well.. it would mean we at least run with debug assertions if built from within the miri repo, but not when building via x.py. We would then have to tell bootstrap separately to build the miri crate with debug assertions.

**Comment by RalfJung** [comment]
It also means showing a warning about profiles being ignored on each and every `cargo` invocation done by `x.py`. That's not really an option IMO.

**Comment by RalfJung** [comment]
> We would then have to tell bootstrap separately to build the miri crate with debug assertions.

That is the build we ship to users, so it is the most important one here. If that build doesn't end up with overflow checks, we might as well not change anything.

**Comment by RalfJung** [comment]
> Bootstrap will need its own separate logic, but if we had .cargo/config.toml inside this repo, bootstrap would ignore it and only local builds would pick it up

I am not trying to solve a problem in this repo. We can use `RUSTFLAGS` for that, and anyway CI uses debug builds for `./miri test` so we have overflow checks there.

I am trying to solve overflow checks for the build we ship to users.

**Comment by RalfJung** [comment]
> let's go with this PR for now.

Thanks!
@bors r=oli-obk

**Comment by RalfJung** [comment]
Opened https://github.com/rust-lang/miri/issues/2501 to track finding a more elegant solution here.

**Comment by RalfJung** [comment]
We just recently stopped using profiles because they dont work in workspaces - only the profile in the workspace root Cargo.toml is taken into account.

**Pull request merged**
