### PR TITLE
macOs intercepting CCRandomGenerateBytes.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks for the PR!

IIRC we had that function, but removed it since it was not needed for the standard library nor for getrandom.

What is your motivation for adding it?

**Comment by devnexen** [comment]
Do you mean [rust std](https://github.com/rust-lang/rust/blob/11f32b73e0dc9287e305b5b9980d24aecdc8c17f/library/std/src/sys/pal/unix/rand.rs#L186) ?

**Comment by saethlin** [comment]
That's in a function with `#[cfg(not(target_os = "macos"))]`, so why would you want to shim this function on MacOS if the standard library deliberately avoids calling it?

**Comment by oli-obk** [comment]
It's specifically for iOS, not macos. I don't think we have any support for iOS in miri yet.

**Comment by devnexen** [comment]
> It's specifically for iOS, not macos. I don't think we have any support for iOS in miri yet.

ah good to know, no need indeed.

**Pull request closed without merging**
