### PR TITLE
Initialize MemoryExtra with StdRng

### PR DESCRIPTION
**Pull request by christianpoveda**
Related Rust PR: https://github.com/rust-lang/rust/pull/62158

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Please also remove the `Default` derive from `memory::MemoryExtra`.

**Comment by RalfJung** [comment]
@christianpoveda I planned a bit of refactoring for this new `memory.rs` file. To avoid conflicts I think I am going to base that on top of your PR here if you don't mind. :)

**Comment by christianpoveda** [comment]
Go ahead! Happy coding!

**Comment by RalfJung** [comment]
@oli-obk I did the "get stuff our of lib.rs" that we talked about.

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/miri/pull/799, we need this branch in the miri repo already to land it in rustc synchronously.

**Pull request closed without merging**
