### PR TITLE
try to make the Windows CI not rebuild Miri

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
Odd, seems like we are entirely starved for CI runners, both Travis and AppVeyor? Cc @rust-lang/infra

**Comment by pietroalbini** [comment]
Yep, all the queues are filled.

**Comment by RalfJung** [comment]
Dang, that did not help. Cargo still is not doing the same feature resolution for the release build and the install job. (Cc https://github.com/rust-lang/cargo/issues/6983 and @ehuss, but I don't think this is worth deep investigation.)

Still, this change makes things more consistent with Travis, so I still think it is a good idea.

**Comment by ehuss** [comment]
Yea, you'll need to do the same investigation, this time with winapi, to see which additional features are enabled.  Unfortunately winapi has dozens of features, and the set will probably change over time, so it will probably be more trouble than it's worth.

**Comment by RalfJung** [comment]
That rebuild is around 20% if our Windows CI time. But yeah, without even having a Windows machine I am not going to attempt this.^^

**Comment by shepmaster** [comment]
> without even having a Windows machine

[Microsoft offers free (time-limited) VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) which I use successfully for answering Windows-related Rust questions

**Pull request merged**
