### PR TITLE
remove -Zmiri-panic-on-unsupported flag

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/miri/issues/3952, see that issue for discussion.

### CODE REVIEW

**Comment by saethlin** [comment]
> nextest is the better option for "continue running other tests if one test failed"

Nextest does not and cannot support doctests, so this would mean we don't have a way to continue running if one doctest fails.

**Comment by RalfJung** [comment]
Cargo/rustdoc already supports continuing if one doctest fails, I think?

It also runs all doctests concurrently. That's why in miri-test-libstd, doctests are so much faster than unit/integration tests. ;)

**Comment by saethlin** [comment]
Ah of course it does, this is probably the same reason to get a single-threaded doctest run you need `-j1` plus `--test-threads=1`.

**Comment by saethlin** [comment]
So if all use of this flag can be replaced by nextest, why should we keep it at all? I don't *think* I've seen this actually happen, but injecting new unwinding sites into a bunch of unsafe code may cause UB that's only there because of unwinding that can only happen with Miri.

**Comment by RalfJung** [comment]
All right, I now made this just entirely remove the flag. @rust-lang/miri any objections?

**Comment by saethlin** [comment]
No objections.

**Pull request merged**
