### PR TITLE
Add a benchmark of the hang-on-test-failure code path

### PR DESCRIPTION
**Pull request by saethlin**
This is the code pattern that produces the performance problem in https://github.com/rust-lang/miri/issues/2273

I figured out what I was stuck on in https://github.com/rust-lang/miri/pull/2315#discussion_r916387919. For a while I was just doing `let x: &[u8] = &[0u8; 4096];` but that doesn't produce the runtime inside `Stack::item_popped` that I was looking for, I think because this allocation is never deallocated. But with `Vec`, I get the profile I'm looking for.

### CODE REVIEW

**Comment by RalfJung** [comment]
:joy: the test runs OOM on 32bit machines.^^

**Comment by saethlin** [comment]
I'm pretty sure this will pass with size 4096 after https://github.com/rust-lang/miri/pull/2315 due to the ~3x memory reduction that PR provides. But I also think this benchmark makes a poorer case for the implementation details of that PR with the smaller size.

The irony is cruel.

Also I'm pretty sure the fact that the test fails means that `cargo miri test` with a failing test will currently OOM any 32-bit system. But slowly.

**Comment by RalfJung** [comment]
We can also just block this on landing https://github.com/rust-lang/miri/pull/2315. Or increase it back to 4096 in that PR.

**Comment by saethlin** [comment]
I think that making a benchmark slower as part of an optimization PR would be very confusing if someone were to use the benchmarks to evaluate the impact of PRs later.

So for now I think just sharing this up in a PR makes me feel less dishonest about using a new benchmark to justify an implementation choice, and we can land it after #2315, with the larger size.

**Comment by RalfJung** [comment]
Can you rebase and increase the size to 4096 again? Does that work now? :D

**Comment by RalfJung** [comment]
I just noticed we already have [bench-cargo-miri/backtraces/src/main.rs](https://github.com/rust-lang/miri/blob/master/bench-cargo-miri/backtraces/src/main.rs). But that seems to be something else?

**Comment by saethlin** [comment]
Yes. That benchmark exists because I noticed that I'm pretty sure the `Debug` impl for `BacktraceFrame` or whatever I'm formatting there has an oddly low hit rate in the Stack cache.

**Pull request merged**
