### PR TITLE
Add a test for the new `type_name` intrinsic.

### PR DESCRIPTION
**Pull request by ecstatic-morse**
~~Addresses [this comment](https://github.com/rust-lang/rust/pull/60166/files#r289447620) from @RalfJung.~~

~~This makes the `type_name` intrinsic call `librustc_mir::interpret::type_name` instead of `Ty::to_string`.~~

~~I used the implementation of [`eval_const_to_op`](https://github.com/rust-lang/rust/blob/627486af15d222bcba336b12ea92a05237cc9ab1/src/librustc_mir/interpret/operand.rs#L504) as a reference.~~

This now adds a test for the `type_name` intrinsic and removes the miri impl in favor of the in-core one.

### CODE REVIEW

**Comment by oli-obk** [comment]
I'l prefer to wait for https://github.com/rust-lang/rust/pull/61399 to get merged and then remove the impl here

**Comment by RalfJung** [comment]
Okay. @ecstatic-morse 	could you reduce this PR to just the test case, and remove the intrinsic implementation? We can then merge that once the Rust PR lands.

**Comment by ecstatic-morse** [comment]
@RalfJung Done!

**Comment by RalfJung** [comment]
Could you also remove the implementation of the intrinsic from `src/intrinsic.rs`? It should not be needed any more. You'll have to update `rust-version` to point to the latest commit from upstream rustc though.

And please rebase onto current master.

**Comment by RalfJung** [comment]
Oh actually never mind, https://github.com/rust-lang/rust/pull/61498 did not land yet.

**Comment by RalfJung** [comment]
Tests are failing though:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"std::option::Option<i32>"`,
 right: `"core::option::Option<i32>"`', $DIR/intrinsics.rs:14:5
```

**Comment by oli-obk** [comment]
They will keep failing without a bump of the rustc version we're using in CI

**Comment by ecstatic-morse** [comment]
I'll retrigger a CI run when [rust-lang/rust#61498](https://github.com/rust-lang/rust/pull/61498) lands.

**Comment by RalfJung** [comment]
You'll also have to update the `rust-version` file -- we are pinning the version that CI uses.

**Comment by ecstatic-morse** [comment]
@RalfJung 

I updated `rust-version` to the latest nightly and Travis is green.

**Pull request merged**
