### PR TITLE
bump Rust

### PR DESCRIPTION
**Pull request by RalfJung**
My hypothesis is that this will replicate https://travis-ci.com/rust-lang/miri/jobs/220221687 (so we know which commit range caused it).

### CODE REVIEW

**Comment by RalfJung** [comment]
The regression landed with https://github.com/rust-lang/rust/pull/63043; the likely cause is https://github.com/rust-lang/rust/pull/62982.

**Comment by RalfJung** [comment]
Dang, the log is too [long for Travis](https://api.travis-ci.com/v3/job/220230122/log.txt)... but then how can we debug this? :/

**Comment by RalfJung** [comment]
My best guess so far is that it has something to do with the `find_foreign_static` machine hook. That one emulates the existence of `__cxa_thread_atexit_impl` and maybe using the type there is not the right call?

**Comment by RalfJung** [comment]
Relevant part of the log:
```
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::eval_context: CONTINUING(17) getrandom::macos::fetch_getentropy
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: // bb1
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: StorageDead(_6)
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: _4 = move _5 as *const i8 (Misc)
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: _3 = _4
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: StorageDead(_5)
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: _2 = const libc::unix::dlsym(const libc::unix::bsd::RTLD_DEFAULT, move _3) -> bb2
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::eval_context: ENTERING(0) libc::unix::bsd::RTLD_DEFAULT
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: _0 = const -2isize as *mut std::ffi::c_void (Misc)
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: return
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::eval_context: LEAVING(0) libc::unix::bsd::RTLD_DEFAULT
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: // bb2
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: StorageDead(_3)
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: StorageDead(_4)
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: StorageLive(_7)
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: _7 = _2
 INFO 2019-07-28T10:50:36Z: rustc_mir::interpret::step: _0 = const std::mem::transmute::<*mut std::ffi::c_void, std::option::Option<unsafe extern "C" fn(*mut u8, usize) -> i32>>(move _7) -> bb3
```

**Comment by RalfJung** [comment]
Fix submitted at https://github.com/rust-lang/rust/pull/63076

**Comment by RalfJung** [comment]
Why.. did GitHub do that?!?

**Comment by RalfJung** [comment]
With the fix landed in rustc, this should work now.

@bors r+

**Comment by bjorn3** [comment]
> Why... did GitHub do that?!?

Because of the `Fixes a bug` in the other PR's description. The `a bug` is a link to this PR, so `fixes` closes it. If you hover over the `Fixes`, it will say `This pull request closes pull request #862.`

**Comment by RalfJung** [comment]
Looks spurious.

@bors retry

**Pull request merged**
