### PR TITLE
./miri run: directly run binary instead of using 'cargo run'

### PR DESCRIPTION
**Pull request by RalfJung**
This avoids re-building miri without dev dependencies, so it makes `./miri run` a lot faster if `./miri test` was already executed before.

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm, it works everywhere except on Windows... but the file path seems right. The error code translates to `0xC0000135`. Apparently this can mean STATUS_DLL_NOT_FOUND? Damn... we set `-C link-args=-Wl,-rpath,` which successfully prevents similar errors on Unix. What can we do on Windows if we don't want to use `cargo run` to run this binary?

Cc @ChrisDenton

**Comment by RalfJung** [comment]
Maybe using `rustup run` suffices...
@bors r+

**Comment by RalfJung** [comment]
Nope, unfortunately this does not help. :(

**Comment by RalfJung** [comment]
The only other idea I have is to keep using `cargo run` on Windows, and if a Windows dev is sufficiently annoyed by the waiting time this incurs then they can figure out how to fix this :shrug:

**Comment by ChrisDenton** [comment]
A DLL's directory has to be in `PATH` for it to be found or else be in the same directory as the exe.

(Well there are also [other options](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-unpackaged-apps) but they're more complicated)

**Comment by RalfJung** [comment]
So probably we have to add `toolchains/miri/lib/rustlib/x86_64-unknown-linux-gnu/lib` to the PATH so that it can find librustc_driver and libLLVM.

**Comment by RalfJung** [comment]
Let's see...
@bors r+

**Pull request merged**
