### PR TITLE
Avoid using the tests folder for the file manipulation test

### PR DESCRIPTION
**Pull request by christianpoveda**
https://github.com/rust-lang/rust/pull/65278 r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
That was quick, wow! But why would that work? Now it expects the file in the working directory instead of one level down, which still isn't where the file actually is.

**Comment by christianpoveda** [comment]
That works because the test creates the file, then writes to it, then reads from it and then it deletes the file. The first version just assumed the file was there but now we don't need that anymore.

**Comment by RalfJung** [comment]
Ah, that must be in the PR I didn't get to review yet. ;)

**Comment by christianpoveda** [comment]
Heh, yeah that's exactly why. So, this would only pollute the build dir if the test fails, but hopefully travis will catch that issue even before someone decides to bump miri.

**Comment by RalfJung** [comment]
Maybe give the file a better name then in case it doesn't get cleaned up, like `miri_test_fs.txt`?

**Comment by christianpoveda** [comment]
sure

**Pull request merged**
