### PR TITLE
add README section on randomized alignment testing

### PR DESCRIPTION
**Pull request by RalfJung**
also accept odd number of hex digits

@saethlin you mentioned that you liked this snippet, do you think it'd make sense to put it in the README?

### CODE REVIEW

**Comment by RalfJung** [comment]
Also thanks to @nabijaczleweli for the original shell snippet. :)

**Comment by saethlin** [comment]
Yes. I think that overall this is the least-bad thing to suggest. I'm not _excited_ about suggesting that people run a slow interpreter N times, but it does get the job done.

**Comment by nabijaczleweli** [comment]
Admittedly, this may be skewed because I ran this on a flat computer which is hardly representative of A Laptop, but this run completed in like 40+ish minutes on the safe-transmute-rs testsuite for me? Maybe I'm biased from 6-hour ZTS runs, but that's, like, more than fine as a final elimination run I think?

**Pull request merged**
