### PR TITLE
remove some SSE/SSE2 intrinsics that are no longer used by stdarch

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/miri/issues/3691

### CODE REVIEW

**Comment by RalfJung** [comment]
Blocked on https://github.com/rust-lang/stdarch/pull/1584 propagating to the rustc repo.

**Comment by TDecking** [comment]
The stdarch patch will also ensure that the "sqrt.ps.256" case in https://github.com/rust-lang/miri/blob/master/src/shims/x86/avx.rs#L78 will never be reached. This case is still present here.

**Comment by RalfJung** [comment]
Yeah, but sqrt is implemented together with two other functions there so there's not really any code saved by removing that... :shrug: 

The same goes for sse.sqrt.ss, sse.sqrt.ps.

**Comment by RalfJung** [comment]
Hm I guess this removes all uses of `FloatUnaryOp::Sqrt`. So maybe it's worth it after all.

**Comment by TDecking** [comment]
@RalfJung https://github.com/rust-lang/rust/pull/128466 got merged. This PR is no longer blocked.

**Comment by RalfJung** [comment]
Ah, good point, thanks! :)

@bors r+

**Comment by RalfJung** [comment]
Ah, maybe we need the rustup to land first.

**Comment by RalfJung** [comment]
Hm, no... we had a rustup yesterday, so https://github.com/rust-lang/rust/pull/128466 should have been picked up.

**Comment by RalfJung** [comment]
D'oh, this is from a Miri test directly importing the intrinsic.^^

**Pull request merged**
