### PR TITLE
moving out sched_getaffinity interception from linux'shim, FreeBSD su…

### PR DESCRIPTION
**Pull request by devnexen**
…pporting it too.

### CODE REVIEW

**Comment by RalfJung** [comment]
I think it's the num_cpus test (tests/pass-dep/num_cpus.rs) that tests this function on Linux.

**Comment by devnexen** [comment]
done :)

**Comment by RalfJung** [comment]
Actually turns out this is still entirely untested on freeBSD. :(

**Comment by RalfJung** [comment]
It's also not very useful, since all it does is return EINVAL.

**Pull request merged**
