### PR TITLE
Rustup to rustc 1.42.0-nightly (005cf38f7 2019-12-22)

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by oli-obk** [comment]
We're hitting https://github.com/rust-lang/rust/blob/3982d3514efbb65b3efac6bb006b3fa496d16663/src/librustc_mir/interpret/place.rs#L533 now

Probably https://github.com/solson/miri/blob/87f20fede528a2a99c06e6aae480adac91f5ecc2/tests/run-pass/vec-matching-fold.rs#L12

**Comment by oli-obk** [comment]
I can't figure out how to build a self-contained const eval repro :(

**Comment by RalfJung** [comment]
I don't understand that assertion anyway... why does it make any sense?

**Comment by oli-obk** [comment]
> I don't understand that assertion anyway... why does it make any sense?

Good question, I haven't looked into it at all yet.

**Comment by bjorn3** [comment]
When using for example:

```rust
match &[0, 1] as &[u8] {
    [x, y, a @ ..] => {}
    _ => {}
}
```

There will be a `_4 = &(*_1)[0 of 2];` for `x`. This is equivalent to `ConstantIndex { offset: 0, min_length: 2, from_end: false }`. The assertion says that the offset must be less than `min_length`. So for example `_4 = &(*_1)[2 of 2];` would not be allowed.

**Comment by oli-obk** [comment]
Thanks, I now have a minimal repro that works on just nightly without miri

```rust
#![feature(slice_patterns)]

fn main() {
    match &[0, 1] as &[i32] {
        [a @ .., x] => {}
        &[] => {}
    }
}
``` 

Since `from_end` is `true`, the index is `1` and `min_length` is also `1` because `a` could be empty for all the pattern knows.

**Comment by oli-obk** [comment]
Fix PR: https://github.com/rust-lang/rust/pull/67546

**Comment by RalfJung** [comment]
@bors r+
(can't test locally as the toolchain download takes hours despite my 50 MBit/s connection :/ stupid AWS )

**Pull request merged**
