### PR TITLE
Add a benchmark for creating large uninit allocations

### PR DESCRIPTION
**Pull request by saethlin**
Extracted from https://github.com/rust-lang/miri/issues/3637

I used this program to confirm that https://github.com/rust-lang/rust/pull/125633 has the desired effect.

### CODE REVIEW

**Comment by saethlin** [comment]
That is strange. The only docs I can find suggest this should fit comfortably on a GitHub-hosted runner: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Comment by RalfJung** [comment]
Note that on Windows we're using a 32bit target as the host. Not sure how Windows manages the address space there, maybe it keeps half of it for the kernel so there's only 2GB total for the program?

**Comment by saethlin** [comment]
Right. I was trying to avoid doing that because the effect size shrinks, but of course a little loop fixes that.

**Comment by RalfJung** [comment]
How long does the benchmark take (with the fix)?

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/125633 landed, but a `./miri rustc-pull` will be needed before we have it available in the repo.

**Comment by saethlin** [comment]
> How long does the benchmark take (with the fix)?

200 ms per iteration with the fix. Without the fix, it's 800 ms per iteration. So I think it would be fair to land this without the fix, because it's already one of our faster benchmarks.

**Comment by RalfJung** [comment]
Makes sense, thanks!
@bors r+

**Pull request merged**
