### PR TITLE
Normalize column numbers

### PR DESCRIPTION
**Pull request by est31**
Needed by https://github.com/rust-lang/rust/pull/79002

### CODE REVIEW

**Comment by est31** [comment]
I can't run miri tests with `./x.py test --stage 1 src/tools/miri` because `1.50.0-dev` is apparently not a valid Rust version number. So no idea whether it fixes the issue pointed out here: https://github.com/rust-lang/rust/pull/79002#issuecomment-727266709

**Comment by RalfJung** [comment]
Thanks for helping with Miri!

> Needed by rust-lang/rust#79002

Note that it's fine to land a PR that breaks Miri, and then fix Miri separately.

So I don't think we need to support both the case with and without column numbers at the same time.  I'd prefer to instead adjust normalization to expect column numbers to be present.  Also column numbers in `backtrace-std.rs` should not be normalized away; we want to make sure they are correct instead.

**Comment by est31** [comment]
@RalfJung note that it did break the build of the rollup instead of just going through with it and then setting toolstate: https://github.com/rust-lang/rust/pull/79002#issuecomment-727266709 . Not sure what's broken, but maybe the issue is that tests broke instead of just the compile?

So this PR is needed I think.

Also note that on Windows, column numbers are being omitted in debuginfo and thus also won't show up in the backtrace (see https://github.com/rust-lang/rust/issues/42921). Thus I think the test may not require column numbers to be present.

**Comment by RalfJung** [comment]
It broke just the PR CI of the rollup, not the bors build, right? I am pretty sure it would have worked fine in bors. Miri is allowed to break, and something is seriously wrong if that does not work.

> Also note that on Windows, column numbers are being omitted in debuginfo and thus also won't show up in the backtrace (see rust-lang/rust#42921). Thus I think the test may not require column numbers to be present.

Miri uses its own way to obtain debug info. I would be very surprised if what you said is true in Miri.

**Comment by est31** [comment]
@RalfJung alright then I'll change the PR to assume column numbers, and change https://github.com/rust-lang/rust/pull/79002 to remove the miri submodule update.

**Review by RalfJung — APPROVED** [review]
Thanks! I'll merge this once  rust-lang/rust#79002 lands. (`rust-version` will need updating then but I can do that.)

**Comment by RalfJung** [comment]
Two things broke at once, so I had to fix them together in https://github.com/rust-lang/miri/pull/1630. I made your PR part of that. Thanks for helping fixing Miri!

**Pull request closed without merging**
