### PR TITLE
[nit][typo] Fix out of order words.

### PR DESCRIPTION
**Pull request by ttsugriy**

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks for the PR!

However, as far as I know both of these are allowed?

**Comment by saethlin** [comment]
I never expected that working on Miri would push my English skills like it does, but here we are.

It would also be valid English to say
> MIri currently does not check

All these orderings are valid, but they imply slightly different emphasis and the current wording just reads awkwardly. I think I would prefer that we just delete the "currently", because the current wording is just awkward (if I heard someone use it I would start to suspect they are not a native speaker), and with this PR the phrasing implies that we will add this check in the future. And I don't think there's any reason to suggest to the reader that we will.

**Comment by RalfJung** [comment]
Works for me, let's just remove the `currently`.

@ttsugriy can you adjust the PR?

**Comment by RalfJung** [comment]
Let's try this again.

@bors retry

**Pull request merged**
