### PR TITLE
disable sysroot checks for distributed binaries

### PR DESCRIPTION
**Pull request by RalfJung**
This should help with https://github.com/mozilla/nixpkgs-mozilla/issues/198.

### CODE REVIEW

**Comment by bjorn3** [comment]
Another option would be to use `Path::new(rustc_sysroot).normalize() != Path::new(miri_sysroot).normalize()` as check instead of `rustc_sysroot != miri_sysroot`, right?

**Comment by RalfJung** [comment]
We already `canonicalize` and it's not enough.

The problem is that nix creates symlinks for the *files inside the sysroot*, not the sysroot itself.

**Comment by oli-obk** [comment]
Do we need to change rustc to not emit this env var anymore? Or how was it used before?

**Comment by RalfJung** [comment]
I am confused by the question...

cargo-miri runs both `rustc --print sysroot` and `miri --print sysroot` to check that both work with the same sysroot. When developing Miri, it can easily happen that those mismatch, e.g. one might do `./miri install` with one toolchain and then elsewhere `cargo miri test` with a different toolchain and weird stuff happens.

However, that check doesn't work well with how Nix organized the file system, and anyway it should not be needed for miri as distributed with rustup -- this is mostly something that's needed for local development.

**Comment by oli-obk** [comment]
Ah I found it: https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/bootstrap/test.rs#L387-L389 yea, so we just need to remove that at some point because it's just useless now to set it.

**Comment by RalfJung** [comment]
Ah yes, that's right. Let's both try to remember to do this the next time we bump Miri? :D

**Pull request merged**
