### PR TITLE
tests for Box with non-ZST allocator

### PR DESCRIPTION
**Pull request by RalfJung**
Needs something like https://github.com/rust-lang/rust/pull/96198 (+more for the unsizing stuff), or hopefully https://github.com/rust-lang/rust/pull/95576 suffices as well.

### CODE REVIEW

**Comment by DrMeepster** [comment]
I tried this with rust-lang/rust#95576 and it looks like it fixes dereferencing. Of course, unsizing is still broken.

**Comment by RalfJung** [comment]
Ah, good point. I wonder what the codegen backends do for unsizing.

**Comment by DrMeepster** [comment]
Now that https://github.com/rust-lang/rust/pull/95576 has been merged, it's just the unsizing that's left.

**Comment by RalfJung** [comment]
Miri's type validation also still bails on these non-primitive `Box`es. Miri assumes all primitive types are either scalars or scalar pairs, not arbitrarily-sized monsters like `Box<T, A>`...

Stacked Borrows retagging will probably have similar issues.

**Comment by RalfJung** [comment]
I am closing this for now since I think we need a [larger redesign of `Box`](https://github.com/rust-lang/rust/issues/95453#issuecomment-1166378496) to escape the sea of ICEs here.

**Pull request closed without merging**
