### PR TITLE
Rename check_in_alloc to check_inbounds_alloc

### PR DESCRIPTION
**Pull request by lzutao**
Rustup https://github.com/rust-lang/rust/pull/63075
cc https://github.com/rust-lang/rust/issues/63581

### CODE REVIEW

**Comment by RalfJung** [comment]
Sorry, but I already prepared a PR for this quite some time ago: https://github.com/rust-lang/miri/pull/863.

**Comment by RalfJung** [comment]
I wonder how we could avoid this in the future... I guess you could check the open PRs; I have something like "Miri side of X" in their description when they are matching some breaking change on the rustc side.

Btw, for PRs like this, you will also have to update the `rust-version` file. That file documents which version of Rust is supposed to work, and it is the version tested by CI.

**Comment by lzutao** [comment]
Thanks. That's my bad. Feel free to close redundant PRs.

**Comment by RalfJung** [comment]
Ah and please run `./miri test` before submitting a PR. This one would not have passed the test suite, even after adjusting `rust-version`.

**Pull request closed without merging**
