### PR TITLE
Fix wrong lifetime of TyCtxt

### PR DESCRIPTION
**Pull request by lzutao**
Rustup rust-lang/rust#61817

### CODE REVIEW

**Comment by RalfJung** [comment]
Please also update the `rust-version` file to tell CI to use the new version.

**Comment by lzutao** [comment]
Done.

**Comment by RalfJung** [comment]
Awesome, thanks a lot. :)

I was jsut starting to do this update myself, but you were faster. :D

**Comment by RalfJung** [comment]
Oh dang. We can't land this because CI fails until https://github.com/rust-lang/rust/pull/61828 has landed.

Argh, those dependency chains. :/

**Comment by RalfJung** [comment]
Most likely that PR will not make it into the next nightly so we can only land this one here on Sunday, meaning the "latest available Miri" will be broken until at least Monday. :(

**Comment by RalfJung** [comment]
Ah, I can make a Rust PR with an unmerged branch. So I updated https://github.com/rust-lang/rust/pull/61828 to includes this. Please don't force-push or we will all be confused!

**Comment by lzutao** [comment]
Ok sure!

**Comment by RalfJung** [comment]
I made this PR part of https://github.com/rust-lang/miri/pull/775, to make sure we don't get a stale submodule in the rustc repo.

Thanks again for this!

**Pull request closed without merging**
