### PR TITLE
better diagnostics for Tree Borrows + int2ptr casts

### PR DESCRIPTION
**Pull request by RalfJung**
- Entirely reject `-Zmiri-permissive-provenance -Zmiri-tree-borrows` since that combination just doesn't work
- In the int2ptr cast warning, when Tree Borrows is enabled, do not recommend `-Zmiri-permissive-provenance`, instead note that Tree Borrows does not support int2ptr casts

Fixes https://github.com/rust-lang/miri/issues/3764

### CODE REVIEW

**Comment by ohsayan** [comment]
Also, is there a way to suppress the `int2ptr` casts warning when using tree borrows?

**Comment by RalfJung** [comment]
Not really -- since Tree Borrows doesn't support int2ptr casts, not showing the warning seems hazardous. Now that I understand that your original issue was unrelated, we could possibly partially revert this PR -- but it is still the case that Tree Borrows + int2ptr will miss a lot of UB (even more so than usual for int2ptr), and I am not sure how to best communicate that to users.

The warning should be shown only once. Is it so bad that it needs to be hidden?

**Comment by ohsayan** [comment]
@RalfJung I see, and it makes complete sense. Actually, I've been hunting a bunch of bugs down and the int-to-ptr cast warnings filled the logs...because we use them excessively for storing extra pointer metadata using alignment hacks; that's why I was wondering if there was a way around it.

Also, since we use `crossbeam`, as it happens, tests fail when using stacked borrows but pass using tree borrows (and it's a known issue; see crossbeam-rs/crossbeam#545). So yeah, in a bit of a situation. But I can totally see why suppressing `int2ptr` warnings could be dangerous.

**Comment by RalfJung** [comment]
> storing extra pointer metadata using alignment hacks

FWIW this can be done without int2ptr casts using strict provenance, but that currently requires either nightly or using the [sptr crate](https://crates.io/crates/sptr).

**Pull request merged**
