### PR TITLE
cargo-miri: bump `rustc_tools_util` crate

### PR DESCRIPTION
**Pull request by klensy**
This dedupes crate versions in rust repo.

### CODE REVIEW

**Comment by klensy** [comment]
Btw, this
https://github.com/rust-lang/miri/blob/140dd98fdfc526c8da78f33c57815cbda3bdf4bd/cargo-miri/build.rs#L4-L12

can be almost replaced by `setup_version_info!`
https://github.com/rust-lang/rust-clippy/blob/b528cc90bc35a111125bfd2382bfcdcd345cea69/rustc_tools_util/src/lib.rs#L29-L45
except for `RUSTC_RELEASE_CHANNEL`.

**Comment by RalfJung** [comment]
Ah I hadn't seen that macro, nice... do you want to just do that change?

**Comment by klensy** [comment]
This additionally set `RUSTC_RELEASE_CHANNEL`, so i guess it acceptable.

**Comment by RalfJung** [comment]
yeah Miri can just ignore that env var. Thanks!

@bors r+

**Pull request merged**
