### PR TITLE
Place::Local(x) is now Place::Base(PlaceBase::Local(x))

### PR DESCRIPTION
**Pull request by spastorino**
We need to merge this after the beta cut for this https://github.com/rust-lang/rust/pull/58631 to work.
/cc @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
We cannot land this before the rustc PR merges, but you can just break Miri after the beta train left.

**Comment by spastorino** [comment]
@RalfJung and how do we land the PR on rustc with the CI failing because this PR is not in :smile:
I'm not sure how all this stuff works ;).

**Comment by RalfJung** [comment]
Yeah cyclic dependencies are fun. ;)

After Thursday, your PR can land on rustc even if it breaks Miri. The "though shall not break a tool" is only in effect the week before the beta train leaves.

**Comment by spastorino** [comment]
@RalfJung good to know :)

**Comment by spastorino** [comment]
@oli-obk @RalfJung this is mergeable now, just force pushed again because there was a conflict.

**Comment by oli-obk** [comment]
Hm. looks like we need to wait for a nightly.

**Pull request merged**
