### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by RalfJung**
Cc https://github.com/rust-lang/rust/issues/99224

### CODE REVIEW

**Comment by zseri** [comment]
ok, this is weird...
failure on `win32`:
```
tests/pass\concurrency\sync.rs FAILED
command: "D:\\a\\miri\\miri/target\\i686-pc-windows-msvc\\release\\miri.exe" "--edition" "2018" "-Dwarnings" "-Dunused" "--sysroot" "C:\\Users\\runneradmin\\AppData\\Local\\rust-lang\\miri\\cache" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "tests/pass\\concurrency\\sync.rs" "--error-format=json" "-Zmiri-disable-isolation" "-Zmiri-strict-provenance"
Pass got exit code: 1
actual output differed from expected tests/pass\concurrency\sync.stderr
Diff< left / right > :
>error: the main thread terminated without waiting for all remaining threads
>
>note: pass `-Zmiri-ignore-leaks` to disable this check
>
>error: aborting due to previous error
```
but: this test shouldn't even be executed under `win32`...
https://github.com/rust-lang/miri/blob/af2c50fb89840852c5181c6e8aeb7be94d85f8df/tests/pass/concurrency/sync.rs#L1-L2

**Comment by RalfJung** [comment]
Failure is on the win32 *host*. But the tests are running for a different *target*, and `ignore` and `cfg` and everything else in the test are checking the target.

@bors r+

**Pull request merged**
