### PR TITLE
build: Gate only on GHA: remove travis and appveyor ci config

### PR DESCRIPTION
**Pull request by lzutao**
It's been over a week since #1571 merged.
The GHA evaluation is successful.

This PR removes CI config of travis and appveyor.
Now MIRI gates on github actions CI only.

Will need <https://github.com/rust-lang/homu/pull/109> to merge first,
otherwise bors will stuck.

Also, one may need to remove `continuous-integration/appveyor/pr` CI checks
in repo settings or appeveyor website.

### CODE REVIEW

**Comment by RalfJung** [comment]
> Also, one may need to remove continuous-integration/appveyor/pr CI checks
in repo settings or appeveyor website.

Right, both Travis and AppVeyor integration should be removed.
@pietroalbini can you do that?

**Comment by pietroalbini** [comment]
This should be able to land now.

**Comment by RalfJung** [comment]
All right, let's try. :)

@bors r+

**Comment by RalfJung** [comment]
Hm, AppVeyor still seems to trigger a build?

https://ci.appveyor.com/project/rust-lang-libs/miri/builds/35849135

**Comment by pietroalbini** [comment]
By default AppVeyor uses its default settings when no `appveyor.yml` is present. I changed the configuration to skip branches without that file.

**Comment by RalfJung** [comment]
Okay, thanks.

We could also just entirely disable AppVeyor for this repository, if that's a possibility.

**Comment by pietroalbini** [comment]
Ok, deleted the miri project on AppVeyor.

**Comment by RalfJung** [comment]
> bors retry

Why did you want to retry?

**Comment by lzutao** [comment]
My apology! I forgot bors isn't gated on appveyor now :p

**Pull request merged**
