### PR TITLE
rm custom `intrinsics::discriminant_value`

### PR DESCRIPTION
**Pull request by lcnr**
@RalfJung requires https://github.com/rust-lang/rust/pull/69825

### CODE REVIEW

**Comment by lcnr** [comment]
The required PR is now merged. Can you also please update the labels of https://github.com/rust-lang/rust/issues/69821?

**Comment by RalfJung** [comment]
We even bumped `rustc-version` already in another PR, so...

@bors r+

**Comment by RalfJung** [comment]
I don't know what you want me to do with the labels of the issue?

**Comment by lcnr** [comment]
remove `C-feature-request`, add `C-tracking-issue` :smile:

**Comment by RalfJung** [comment]
> remove C-feature-request, add C-tracking-issue smile

done :)

**Comment by RalfJung** [comment]
*sigh* Travis macOS is unreliable, again...

@bors retry

**Comment by lcnr** [comment]
wow

**Pull request merged**
