### PR TITLE
Fix sysroot handling

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
Turns out I screwed up in my last sysroot PR, I hope this PR (updated it) now fixes that.

I also changed it so that the panic from `compile_time_sysroot` surfaces even if `MIRI_SYSROOT` is set; this means we actually test that that panic dos *not* happen as part of the test suite.

**Comment by RalfJung** [comment]
CI looks good. Still, this needs a new review I think.

**Comment by oli-obk** [comment]
lgtm, but I'm confused how this happened. Is it because I created the sysroot hacks in our test suite and thus changes in the miri binary were ignored by our tests since the tests passed their own `--sysroot`?

**Comment by RalfJung** [comment]
What happened is that the test suite in rustc always passes a `--sysroot`, yes. Smae for our test suite here though, and same for `cargo miri`. So I think it has been the case since forever that the fallback code (with no `MIRI_SYSROOT`/`--sysroot`) panicked, it's just that we never ran into that code.

But now I added this sanity check in `cargo miri` that does exactly that.

**Comment by RalfJung** [comment]
Oh also we don't test `cargo miri` at all on the rustc side. Would be great if we could somehow make that happen -- and maybe also recompile libstd there instead of relying on setting `--cfg miri` in bootstrap, which I feel uneasy about.

**Comment by oli-obk** [comment]
> maybe also recompile libstd there instead of relying on setting --cfg miri in bootstrap

You mean via `cargo miri setup` or just straight up adding an additional `libstd-miri` thing in bootstrap that Miri depends on?

**Comment by RalfJung** [comment]
Well ideally the same way users do it, so via `cargo miri setup`.

**Pull request merged**
