### PR TITLE
Add `realloc`

### PR DESCRIPTION
**Pull request by TimDiekmann**
Currently we only have `alloc`, `calloc`, and `free`. Let's complete this and add `realloc` :slightly_smiling_face:

### CODE REVIEW

**Comment by RalfJung** [comment]
Unlike `__rust_realloc` and `malloc`, this has no special handling for `size == 0`. Why doesn't it need that?

**Comment by TimDiekmann** [comment]
Good catch, I'll add this. As `malloc` returns `nullptr` on zero size, I think, `realloc` should also return `nullptr`?

**Comment by TimDiekmann** [comment]
Hmm, as `libc::realloc` with `size == 0` is implementation defined, it should result in an error.

**Comment by RalfJung** [comment]
`malloc(0)` is also implementation-defined -- but it's not undefined or so, it just doesn't say whether it returns NULL or some other pointer (that may not be used).

IMO we should do the same for `realloc`.

**Pull request merged**
