### PR TITLE
experiment with macOS M1 runners

### PR DESCRIPTION
**Pull request by RalfJung**
Try running our macOS CI on the new free M1 runners. This would mean that our 3 jobs run 3 different OSes and 3 different host CPU architectures. :)

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm, that doesn't seem to work -- they don't have cargo?
According to [this](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md) Ruts is supposed to be installed.

**Comment by RalfJung** [comment]
Oh so the problem was the cache, interesting. No idea how a bad cache would lead to that kind of error, probably because some binaries have the wrong architecture or so?

And the build was very fast, too.
@rust-lang/miri what do you think, shall we give these runners a try? It's easy to switch back to the old runners if we're getting problems.

**Comment by RalfJung** [comment]
One point I didn't realize is that this is still a tier 2 target. So there's some risk things break as rustc CI doesn't cover everything.

But it's also easy to revert this PR in the future, should it become a problem.

**Comment by RalfJung** [comment]
Judging from [this GH announcement](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/), `macos-latest` will switch to M1 machines some time soon (April - June). So we have to either do something like this PR or set the runner to `macos-12` to get more time to migrate.

**Comment by saethlin** [comment]
I do not think the risk is very high. If aarch64 MacOS breaks, too many of us will know because we develop on it. Speed is nice. No objection to merging this.

**Comment by RalfJung** [comment]
> I do not think the risk is very high. If aarch64 MacOS breaks, too many of us will know because we develop on it. Speed is nice. No objection to merging this.

Yeah, makes sense. And additionally we can serve as a canary for Rust compiler stuff breaking on M1 hosts, which is a good service to the compiler team. This target is clearly going to become tier 1, so we may as well be part of slowly increasing test coverage.

@bors r+

Cc @shepmaster since you seem to be tracking M1 progress. :)

**Comment by shepmaster** [comment]
> this is still a tier 2 target

To the best of my knowledge, this is in name only. Right when the M1 runners came out we enabled tests and other things that the tier 1 platforms do. It’s mostly waiting on me to do the paperwork for the promotion and I’m just waiting for a bit of stability on GitHub’s side over a medium-length time period. 

> switch to M1 machines some time soon (April - June)

I had missed that, so that might be the sign I was waiting for…

**Pull request merged**
