### PR TITLE
Rustup for rustc-dev

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes fallout from https://github.com/rust-lang/rust/pull/64823

### CODE REVIEW

**Comment by bjorn3** [comment]
```
error[E0463]: can't find crate for `syntax`

 --> src/lib.rs:9:1

  |

9 | extern crate syntax;

  | ^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by mati865** [comment]
cc @cuviper

**Comment by RalfJung** [comment]
rustup-toolchain-install-master has been fixed. Let's try again.

@bors r+

**Comment by RalfJung** [comment]
Now that is weird. Let us do some debugging.

@bors r+

**Comment by mati865** [comment]
FIY `rustc-dev` PR is being temporary reverted: https://github.com/rust-lang/rust/pull/65342

**Comment by RalfJung** [comment]
Yeah windows-msvc also seems broken.

@bors r- retry

**Pull request closed without merging**
