### PR TITLE
Add clippy cross-checking support to CI

### PR DESCRIPTION
**Pull request by RossSmyth**
I can't run this on my computer because jemallocator isn't supported on Windows. So let's see if CI is happy with this.

### CODE REVIEW

**Comment by RossSmyth** [comment]
```
2024-02-25T19:44:42.6885970Z   configure: error: in `/home/runner/work/miri/miri/target/x86_64-apple-darwin/debug/build/jemalloc-sys-d7684c6ecce9a528/out/build':
2024-02-25T19:44:42.6887631Z   configure: error: C compiler cannot create executables
2024-02-25T19:44:42.6888730Z   See `config.log' for more details
```

**Comment by RalfJung** [comment]
Doesn't seem like it's possible to run clippy for targets that one can't build binaries for. So we'll have to run these on their respective native hosts, I guess?

**Comment by saethlin** [comment]
@RossSmyth We only have the jemalloc dependency to fix this issue: https://github.com/rust-lang/miri/issues/3255 which we shouldn't be subject to in a check build.

So I'd support a way to toggle it off for cross-checking.

**Comment by RalfJung** [comment]
That still doesn't seem to be working
```
error[E0463]: can't find crate for `either`
  --> src/lib.rs:52:1
   |
52 | extern crate either; // the one from rustc
   | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `rustc_apfloat`
  --> src/lib.rs:54:1
   |
54 | extern crate rustc_apfloat;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`
```

**Comment by RalfJung** [comment]
I think we have to give up on the cross-clippy thing. We can just add a clippy run to the end of the regular CI job to ensure we have coverage.

**Comment by RossSmyth** [comment]
Yeah I've pretty much given up on it. Too many weird things to account for.

**Pull request closed without merging**
