### PR TITLE
Address reuse improvements and fixes

### PR DESCRIPTION
**Pull request by RalfJung**
- when an address gets reused, establish a happens-before link in the data race model
- do not reuse stack addresses, and make the reuse rate configurable

Fixes https://github.com/rust-lang/miri/issues/3450

### CODE REVIEW

**Comment by RalfJung** [comment]
I excluded stack allocations from reuse, and made the reuse rate configurable.

@bors r+

**Comment by RalfJung** [comment]
This actually still has a quite significant impact on data race detection; I suspect this is due to heap allocations in the thread spawning logic. I'm not sure what the best way forward is here... other than reducing the reuse rate drastically. With a reuse rate of 25%, the simple data race I checked is still found around 70% of the time (but it's 100% without reuse).

I think the rate will be better with real programs; the issue is that in these tests the threads exist only for a very short time so there's a real chance it never gets preempted and so the first thread is done before the second thread starts, and therefore allocations can be reused. If I add a simple `for _ in 0..100 {}` to the first thread, the data race is detected ~100% of the time even with address reuse.

We could of course also just not to any reuse across threads, then we also will never add spurious synchronization. But for heap allocations that's not real either.

**Comment by RalfJung** [comment]
OTOH, real programs will also do a bunch of stuff on the heap, which again increases the chance of address reuse inducting synchronization.

My current inclination is to add some extra randomness that makes address reuse across thread boundaries a lot less likely than address reuse within a single thread.

**Comment by saethlin** [comment]
> With the cross-thread reuse rate of 10%, the simple data race tests still detect the race 80% of the time when preemption is disabled (and ~100% of the time when preemption is enabled).

That seems fine to me. Anyone seriously looking to find data races should have preemption enabled.

**Comment by RalfJung** [comment]
Yeah... though it's hard to say what this will do for other cases. Not sure how many people run concurrency tests in a loop in Miri to give races more than one chance to appear.

But for now, let's go ahead with this, we can always re-adjust later if we realize that data race detection has become too non-deterministic.

@bors r+

**Pull request merged**
