### PR TITLE
whitelist platforms where panicking should work

### PR DESCRIPTION
**Pull request by RalfJung**
@CAD97 [proposed](https://github.com/rust-lang/miri/issues/1059#issuecomment-601217992) trying to get a better error for failed panics on Windows.

Could you test if this works for you?

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm no this will probably be too late, actually... I think the RwLock is acquired earlier. We probably need to abort already in `panic_impl`.

**Comment by RalfJung** [comment]
I moved the check further "up", i.e. it is now checking earlier and hopefully should no longer reach the bad `RwLock` on Windows.

**Comment by CAD97** [comment]
I would test it but I'm having trouble getting miri to build from my (windows) machine. Whichever path I'm trying I fail to find `rustc_apfloat`.

**Comment by RalfJung** [comment]
Well, let's see if this test passes then.
@bors r+

**Comment by RalfJung** [comment]
Nope... there's no "hooked" function on Windows that we can intercept to get a proper error. :/

**Comment by bjorn3** [comment]
> I would test it but I'm having trouble getting miri to build from my (windows) machine. Whichever path I'm trying I fail to find rustc_apfloat.

Is the `rustc-dev` component installed?

**Comment by CAD97** [comment]
Ah, that's almost certainly it.

**Comment by bjorn3** [comment]
Filled rust-lang/rust#70157 for a better suggestion.

**Comment by RalfJung** [comment]
All right I think this covers all entry points. Let's see what CI says.
@CAD97 could you also test this?

@bors r+

**Pull request merged**
