### PR TITLE
cargo miri: add support for '--many-seeds'

### PR DESCRIPTION
**Pull request by RalfJung**
to run the program / tests many times with different seeds: `cargo miri run --many-seeds` / `cargo miri test --many-seeds`.

@rust-lang/miri any opinion on the flag name here? Should it be `-Zmiri-many-seeds` or is `--many-seeds` fine?

Fixes https://github.com/rust-lang/miri/issues/3546

### CODE REVIEW

**Comment by saethlin** [comment]
I think `--many-seeds` is better. Honestly I don't see any reason to claim this is unstable/experimental, we've been doing this many seeds thing for years and I think it has proven its value.

**Comment by RalfJung** [comment]
All right, let's land this then. We can always adjust this later.

@bors r+

**Comment by ibraheemdev** [comment]
`--many-seeds` doesn't seem to run integration tests, was this intentional?

**Comment by RalfJung** [comment]
I am not sure what you mean. Test selection is independent of this flag.

Please file an issue with reproducible instructions.

**Pull request merged**
