### PR TITLE
Add option to disable alignment check

### PR DESCRIPTION
**Pull request by RalfJung**
Requires https://github.com/rust-lang/rust/pull/71101
Fixes https://github.com/rust-lang/miri/issues/1326

### CODE REVIEW

**Comment by thomcc** [comment]
Will miri still report actual loads from unaligned addresses?

Either way this is great -- it's been frustrating to disable tests for miri because they were *too* thorough and checked that every possible alignment and size combination didn't result in a misaligned load or OOB read.

**Comment by RalfJung** [comment]
> Will miri still report actual loads from unaligned addresses?

That is the exact check this disables. I am confused by your question.

> Either way this is great -- it's been frustrating to disable tests for miri because they were too thorough and checked that every possible alignment and size combination didn't result in a misaligned load or OOB read.

Except for https://github.com/rust-lang/miri/issues/1074, I do not know of a case where Miri is too thorough. Alignment errors otherwise are UB and indicate a bug in the program.

**Comment by thomcc** [comment]
> Except for #1074, I do not know of a case where Miri is too thorough. Alignment errors otherwise are UB and indicate a bug in the program.

I believe that's the case I mean. Basically I have code that manually aligns a pointer using pointer arithmetic. I test this with a very large number of possible input alignments and lengths to ensure it's sane, but miri assumes that any manually-aligned pointer is still invalid.

I had thought this was for disabling miri complaints about that case -- I guess it's about all cases. That doesn't bother me that much, since I generally have have a wrapper around ptr::read which asserts the alignment is correct for stuff like this, but yeah, I must have misunderstood.

**Comment by RalfJung** [comment]
> I had thought this was for disabling miri complaints about that case

No. That would be resolving https://github.com/rust-lang/miri/pull/1332. This does not resolve that issue, but it offers a work-around (at the expense of possibly missing bugs).

**Pull request merged**
