### PR TITLE
Miri rename undef uninit

### PR DESCRIPTION
**Pull request by pnadon**
The changes made here are related to [issue #71193 on Rust](https://github.com/rust-lang/rust/issues/71193), and the pull request [74664 on Rust](https://github.com/rust-lang/rust/pull/74664).

1. renamed `ScalarMaybeUninit::not_undef` to `check_init`
2. renamed `Immediate::to_scalar_or_undef` to `Immediate::to_scalar_or_uninit`

### CODE REVIEW

**Comment by RalfJung** [comment]
This looks good, thanks. :)

**Comment by pnadon** [comment]
I will check the build on my local machine, using rustc with the changes made in the previously mentioned PR

**Comment by pnadon** [comment]
The local build I did of Miri, using the steps defined [here](https://github.com/rust-lang/miri/blob/master/CONTRIBUTING.md#building-and-testing-miri) compiled successfully using the changes made [in this pull request](https://github.com/rust-lang/rust/pull/74664).

**Comment by RalfJung** [comment]
Awesome, thanks for checking that :)

**Comment by RalfJung** [comment]
@pnadon can you extend this PR to update the `rust-version` file, now that your rustc PR landed?

**Comment by pnadon** [comment]
@RalfJung it should be the hash for the commit below, correct?

https://github.com/rust-lang/rust/commit/13f9aa190957b993a268fd4a046fce76ca8814ee

**Comment by RalfJung** [comment]
Yes, the hash of latest master.

**Comment by pnadon** [comment]
It seems as though there is a conflict due to someone changing the `rust-version` since I started working on this.

**Comment by RalfJung** [comment]
Ah good point... that someone is probably me. ;)
Can you rebase your PR on top of current master, and then do the rust-version edit again?

**Comment by pnadon** [comment]
@RalfJung done!

**Comment by RalfJung** [comment]
@pnadon CI isn't happy, something is not building:
```
error[E0599]: no method named `not_undef` found for enum `rustc_mir::interpret::ScalarMaybeUninit<stacked_borrows::Tag>` in the current scope

   --> src/shims/foreign_items.rs:203:50

    |

203 |                 let ptr = this.read_scalar(ptr)?.not_undef()?;

    |                                                  ^^^^^^^^^ method not found in `rustc_mir::interpret::ScalarMaybeUninit<stacked_borrows::Tag>`
```

**Comment by pnadon** [comment]
I checked just now, and the error was due to upstream insertions, one of which used "not_undef". The latest commit fixes this.

**Comment by RalfJung** [comment]
Thanks. :)
@bors r+

**Pull request merged**
