### PR TITLE
bump actions/cache to v4

### LINKED ISSUE #3518: `ci.yml` uses `deprecated` version of `Node.js`
image

That image shows warnings about CI using an action that uses a `deprecated` version of `Node.js`.

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #3518.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
# Without this change

image

# With this change

image

**Comment by saethlin** [comment]
I'm happy to take the second commit, but not the formatting changes. For example, consider some other drive-by contributor who has their YAML config set up for 2-space indentations. They'd submit essentially the opposite change as you have with the same justification.

Drop the first commit and I'll approve the version bump of the `checkout` action. If use a YAML formatter, I at least want to pin its settings and discuss that separately.

**Comment by RalfJung** [comment]
Thanks! Github *really* likes people doing manual version bumps all the time...

@bors r+

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
